### ISSUE TITLE
BUG: Not returning dict

### ISSUE THREAD

**Issue by pedromorgan** [raisoblast/bottle-pgsql#2]
After a bit of research have found that

```
  cur = con.cursor(cursor_factory=psycopg2.extras.DictCursor) 
```

should be

```
cur = con.cursor(cursor_factory=psycopg2.extras.RealDictCursor)
```

https://github.com/raisoblast/bottle-pgsql/blob/master/bottle_pgsql.py#L92

Stackoverflow answer
http://stackoverflow.com/questions/6739355/dictcursor-doesnt-seem-to-work-under-psycopg2

**Comment by raisoblast** [comment]
thanks @pedromorgan, send me a PR :)

**Comment by gzur** [comment]
This patch has not been pushed to pip yet.

**Comment by raisoblast** [comment]
thanks @gzur, i just pushed the patch to pypi
